#26 - integration tests for contracts
maraoz/rewilder pull request #90
Opened 2021-09-23 21:35 UTC by jparnaudo

Script for testing `RewilderDonationCampaign` with Gnosis Safe multisig 2of3 wallet.

To run script
- make sure you have gnosis safe-contracts deployed into your localhost node
`yarn install && npx yarn hardhat --network localhost deploy`

- run test
`npx hardhat run ./scripts/gnosis-multisig-test.js --network localhost`

2021-09-23 21:56 UTC, maraoz requested changes

2021-09-23 21:56 UTC, maraoz commented on package.json
> +    "@material-ui/core": "^4.12.3",
remove unneeded dependency pls

2021-09-23 21:56 UTC, maraoz commented on package.json
> +    "ethers": "5.4.5",
was this change intended?

2021-09-24 14:27 UTC, jparnaudo commented on package.json
> +    "ethers": "5.4.5",
Yes, see:
https://docs.ethers.io/v5/api/signer/#Signer-signTypedData

2021-09-24 18:31 UTC, maraoz approved these changes
LGTM, ready to merge after you include these polishing changes: https://github.com/jparnaudo/rewilder/pull/3

2021-09-24 18:57 UTC, merged